In [1]:
import pandas as pd
import numpy as np
# !pip install openpyxl

In [2]:

original_df = pd.read_excel(r'excel files/Required Plan.xlsx')

In [3]:
# extract the first word from 'Arabic Name' and create a new column 'new Name'

original_df['new Name'] = original_df['Arabic Name'].str.split(" ").str[0]


# extract the number from the name which refer to the concentration of the drug

original_df['conc'] = original_df['Arabic Name'].str.extract('(\d+)')


# donot need supplier type column so we will drop it

original_df.drop(['supplier type'], axis = 1, inplace = True)

original_df.head(5)

,Product ID,Item,Arabic Name,Price,required,new Name,conc
0,21462,MILGA 40 F.C. TAB,ميلجا 40 قرص,68.0,2415.250,ميلجا,40
1,3644,ESMORAP 40MG 14 CAPS.,ازموراب 40 مجم 14 كبسولة,94.0,1491.500,ازموراب,40
2,2088,DIBAVALLY PLUS 50/1000 MG 28 TABS.,ديبافالي بلس 50/1000مجم 28 قرص,140.0,1294.000,ديبافالي,50
3,7319,ZURCAL 40 MG 28 GASTRO RESISTANT TAB.,زوركال 40 مجم 28 قرص,132.0,1212.250,زوركال,40
4,23122,ASPOCID 75MG 30TAB.,اسبوسيد 75 مجم 30 قرص,21.0,1089.334,اسبوسيد,75

In [4]:
supplier_1 = pd.read_excel(r'excel files/supplier 1.xlsx')
supplier_1

    أرصده المخازن\n               Unnamed: 1 Unnamed: 2  Unnamed: 3
0               NaN                      NaN        NaN         NaN
1               NaN                      NaN        NaN         NaN
2               NaN                      NaN        NaN         NaN
3               NaN                      NaN        NaN         NaN
4         رقم الصنف                إسم الصنف      السعر   خصم اساسى
..              ...                      ...        ...         ...
519            2624      هيرو اف ايه اتش لبن        599          13
520             514           هيرو ال اف لبن        319          14
521             428        هيرو او ار اس لبن        255          18
522            1213        ويل مان اوريجينال        160          29
523            1459  وينزوكسيب 90 مللى اقراص        136          30

[524 rows x 4 columns]

In [5]:
# remove the first 4 rows which are not needed and set the 5th row as header

supplier_1.columns = supplier_1.iloc[4]


supplier_1.drop([0,1,2,3,4], axis = 0, inplace =True)


# unifying the column names to match other suppliers dataframes

supplier_1.rename(columns = {'رقم الصنف' : 'Product ID',
                       'إسم الصنف' : 'Arabic Name',
                       'السعر' : 'Price',
                       supplier_1.columns[3] : 'supplier_1'}, inplace = True)



# extract the first word from 'Arabic Name' and create a new column 'new Name' as we did for original_df

supplier_1['new Name'] = supplier_1['Arabic Name'].str.split(" ").str[0]

# extract the number from the name which refer to the concentration of the drug

supplier_1['conc'] = supplier_1['Arabic Name'].str.extract('(\d+)')


# choose the columns we need

supplier_1 = supplier_1[['new Name','Price','supplier_1','conc']]

supplier_1.head(5)

4       new Name Price supplier_1 conc
5         اتركتا   300         29  NaN
6       اتروزيمب   174         34   10
7  اتروزيمب10/10   174         34   10
8         اتومكس    90         32   10
9        ادفوكول   106         30    2

In [6]:
supplier_2 = pd.read_excel(r'excel files/supplier2.xlsx')
supplier_2

,نقدى,سعر ج,الكود,الشركه,الصنف
0,37.0,21.0,2185,ايبيكو للصناعات الدوائية,ابروفاستين 10 مجم اقراص باكو10 كارتونه240
1,29.0,50.0,5342,طيبة للصناعات الدوائية,ابريتيف شراب 120مل باكو25 ارضي
2,33.0,43.5,8061,ايبيكو للصناعات الدوائية,ابى زيثرو 500 اقراص باكو10
3,29.0,32.5,7854,ايبيكو للصناعات الدوائية,ابى زيثرو معلق 200 مجم 30ملج شراب ارضي
4,25.0,28.0,8318,امون للادوية,ابياموكس كبسول باكت 45
...,...,...,...,...,...
1087,32.0,28.0,2314,ادويا فارم,يوريبان شراب باكو25حصرى
1088,32.0,36.0,6960,ادويا فارم,يوريبان اقراص سعر 36 باكت 200حصري
1089,28.0,90.0,4775,يونيفارم,يونى فركتوز برطمان باكت20
1090,41.0,9.5,4686,يونيفارم,يوني سيتامول نقط سيتال
1091,36.0,20.0,498,المهن الطبية الدوائية,يونيكتام 750 مجم فيال باكو 64

In [7]:
supplier_2.rename(columns = {supplier_2.columns[2] : 'Product ID',
                         supplier_2.columns[4] : 'Arabic Name',
                         supplier_2.columns[1] : 'Price',
                         supplier_2.columns[3] : 'Company',
                         supplier_2.columns[0] : 'supplier_2'}, inplace = True)


supplier_2['new Name'] = supplier_2['Arabic Name'].str.split(" ").str[0]


supplier_2['conc'] = supplier_2['Arabic Name'].str.extract('(\d+)')


supplier_2 = supplier_2[['new Name','Price','supplier_2','conc']]

supplier_2.head(5)

     new Name  Price  supplier_2 conc
0  ابروفاستين   21.0        37.0   10
1     ابريتيف   50.0        29.0  120
2         ابى   43.5        33.0  500
3         ابى   32.5        29.0  200
4    ابياموكس   28.0        25.0   45

In [8]:
supplier_3 = pd.read_excel(r'excel files/supplier3.xlsx')
supplier_3

     جمله  سعر ج                       الصنف
0    29.0   50.0    ابريتيف شراب فاتح للشهيه
1    28.0   90.0         ابى جرو مكمل غذائى
2    30.0   55.0                 ابيدرم كريم
3    32.0   60.0             ابيفورتيل كبسول
4    27.0  126.0          ابيكسيدون 3م اقراص
..    ...    ...                         ...
734  33.0  160.0  وايت مينز وايت غسول للبشره
735  25.0  175.0               وصايا زيت شعر
736  42.0   58.0                      وى جيل
737  28.0   23.5             يوروسولفين فوار
738  30.0   18.0            يوريكنترول اقراص

[739 rows x 3 columns]

In [9]:
supplier_3.rename(columns = {supplier_3.columns[2] : 'Arabic Name',
                         supplier_3.columns[1] : 'Price',
                         supplier_3.columns[0] : 'supplier_3'}, inplace = True)



supplier_3['new Name'] = supplier_3['Arabic Name'].str.split(" ").str[0]


supplier_3['conc'] = supplier_3['Arabic Name'].str.extract('(\d+)')


supplier_3 = supplier_3[['new Name','Price','supplier_3','conc']]

supplier_3.head(5)

    new Name  Price  supplier_3 conc
0    ابريتيف   50.0        29.0  NaN
1        ابى   90.0        28.0  NaN
2     ابيدرم   55.0        30.0  NaN
3  ابيفورتيل   60.0        32.0  NaN
4  ابيكسيدون  126.0        27.0    3

In [10]:
supplier_4 = pd.read_excel(r'excel files/supplier4.xlsx')
supplier_4

    Unnamed: 0                   Unnamed: 1 Unnamed: 2
0          NaN                          NaN        NaN
1        مندوب                        الصنف      سعر ج
2            7       ابيجونال 75 وحدة امبول        200
3         18.5            ابيدرا سولوستار**      472.5
4           20  ابيفاسى 5000 وحدة 1 امبول**        211
..         ...                          ...        ...
372         28         وان تو ثري شراب جديد       19.5
373         42                وى جيل للرجال         58
374          3          يوراليت يو حبيبات**        256
375         28       يونى بيوتيك 500 - 5قرص         45
376       14.5           يونى تريكسات امبول        220

[377 rows x 3 columns]

In [11]:
supplier_4.columns = supplier_4.iloc[1]

supplier_4.drop([0,1], axis = 0, inplace =True)


supplier_4.rename(columns = {supplier_4.columns[1] : 'Arabic Name',
                         supplier_4.columns[2] : 'Price',
                         supplier_4.columns[0] : 'supplier_4'}, inplace = True)


supplier_4.dropna(inplace = True)


supplier_4['new Name'] = supplier_4['Arabic Name'].str.split(" ").str[0]



supplier_4['conc'] = supplier_4['Arabic Name'].str.extract('(\d+)')



supplier_4 = supplier_4[['new Name','Price','supplier_4','conc']]

supplier_4.head(5)

1   new Name  Price supplier_4  conc
2   ابيجونال    200          7    75
3     ابيدرا  472.5       18.5   NaN
4    ابيفاسى    211         20  5000
5  ابيفورتيل     60         35    30
6  ابيكوبريد     48       37.5     5

In [12]:
supplier_5 = pd.read_excel(r'excel files/supplier5.xlsx')

supplier_5

     جملة  سعر ج  الكود                    الصنف
0    29.0   50.0  15105   ابريتيف شراب فاتح شهيه
1     5.0   15.0   4145              ابيدون شراب
2    29.0   12.0  11777            ابيكوجيل شراب
3    34.0   18.0   8127             ابيماج فوار
4    35.0   33.0  11618  ابينوسين--ب--فورت امبول
..    ...    ...    ...                      ...
466  15.0  128.0    516             ياسمين اقراص
467  29.0  192.5  14721          يورونيميا امبول
468  38.0  165.0  15078           يوفى كريم75 جم
469  29.0   95.0  14063             يوميجا  كيدز
470  21.0  120.0  14907          يوميجا دى اقراص

[471 rows x 4 columns]

In [13]:
supplier_5.rename(columns = {supplier_5.columns[3]: 'Arabic Name',
                       supplier_5.columns[1] : 'Price',
                       supplier_5.columns[0] : 'supplier_5'}, inplace = True)


supplier_5['new Name'] = supplier_5['Arabic Name'].str.split(" ").str[0]


supplier_5['conc'] = supplier_5['Arabic Name'].str.extract('(\d+)')


supplier_5 = supplier_5[['new Name','Price','supplier_5','conc']]


supplier_5.head(5)

            new Name  Price  supplier_5 conc
0            ابريتيف   50.0        29.0  NaN
1             ابيدون   15.0         5.0  NaN
2           ابيكوجيل   12.0        29.0  NaN
3             ابيماج   18.0        34.0  NaN
4  ابينوسين--ب--فورت   33.0        35.0  NaN

In [14]:
supplier_6 = pd.read_excel(r'excel files/supplier6.xlsx')
supplier_6

    أرصده المخازن\n                    Unnamed: 1 Unnamed: 2  Unnamed: 3
0               NaN                           NaN        NaN         NaN
1               NaN                           NaN        NaN         NaN
2               NaN                           NaN        NaN         NaN
3               NaN                           NaN        NaN         NaN
4         رقم الصنف                     إسم الصنف      السعر   خصم اساسى
..              ...                           ...        ...         ...
789           11927              يورونيميا امبول         120          25
790            2510            يوريبان / 36 جنية          36          31
791            2278  يوريبان شرابا جديد كرتونه 25         28          33
792            3285         يورينكس كبسول سعر17ج          17           6
793           13907    يونيكتام 750 فيال سعر جديد         20          36

[794 rows x 4 columns]

In [15]:
supplier_6.columns = supplier_6.iloc[4]


supplier_6.drop([0,1,2,3,4], axis = 0, inplace =True)


supplier_6.rename(columns = {'رقم الصنف' : 'Product ID',
                       'إسم الصنف' : 'Arabic Name',
                       'السعر' : 'Price',
                       supplier_6.columns[3] : 'supplier_6'}, inplace = True)


supplier_6['new Name'] = supplier_6['Arabic Name'].str.split(" ").str[0]


supplier_6['conc'] = supplier_6['Arabic Name'].str.extract('(\d+)')


supplier_6 = supplier_6[['new Name','Price','supplier_6','conc']]

supplier_6.head(5)

4       new Name Price supplier_6 conc
5        ابرافنت  47.5         21  NaN
6            ابى    90         34  NaN
7   ابياموكس400م    47         21  400
8     ابيدروكسيل    29         33    1
9  ابيدروكسيل500    20         35  500

In [16]:
supplier_7 = pd.read_excel(r'excel files/supplier7.xlsx')
supplier_7

                  أرصده المخازن\n Unnamed: 1  Unnamed: 2
0                             NaN        NaN         NaN
1                             NaN        NaN         NaN
2                             NaN        NaN         NaN
3                             NaN        NaN         NaN
4                       إسم الصنف      السعر   خصم اساسى
..                            ...        ...         ...
959   يوناسين 750  فيال/ سعر جديد         28          26
960  يونى بيوتك 500  مجم/هاى فارم         45          27
961             يونى تريكسات50مجم        220          10
962      يونيفيرسال كريم سعر جديد         75          24
963            يونيكتام 1500 فيال         39          36

[964 rows x 3 columns]

In [17]:
supplier_7.columns = supplier_7.iloc[4]


supplier_7.drop([0,1,2,3,4], axis = 0, inplace =True)


supplier_7.rename(columns = {supplier_7.columns[0]: 'Arabic Name',
                         supplier_7.columns[1]: 'Price',
                         supplier_7.columns[2] : 'supplier_7'}, inplace = True)


supplier_7['new Name'] = supplier_7['Arabic Name'].str.split(" ").str[0]


supplier_7['conc'] = supplier_7['Arabic Name'].str.extract('(\d+)')


supplier_7 = supplier_7[['new Name','Price','supplier_7','conc']]

supplier_7.head(5)

4         new Name Price supplier_7  conc
5       اباندروكير    64       30.5   NaN
6  ابيروفاستين10جم    21         39    10
7       ابيسنو4000   175         19  4000
8         ابيسيفين    45         37     1
9         ابيسيفين    55         24     2

In [18]:
supplier_8 = pd.read_excel(r'excel files/supplier8.xlsx')
supplier_8

    أرصده المخازن\n                      Unnamed: 1 Unnamed: 2  Unnamed: 3
0               NaN                             NaN        NaN         NaN
1               NaN                             NaN        NaN         NaN
2               NaN                             NaN        NaN         NaN
3               NaN                             NaN        NaN         NaN
4         رقم الصنف                       إسم الصنف      السعر   خصم اساسى
..              ...                             ...        ...         ...
428            9946            هيدروكورتيزون امبول          17           3
429            8258                    هيرودكس سيرم        175          37
430           11853  هيرودكس شامبو ضد القشرة 250ملل        142          35
431            6637                    هيرودكس كريم        148          35
432            4880                   هيموجيت امبول         87          30

[433 rows x 4 columns]

In [19]:
supplier_8.columns = supplier_8.iloc[4]


supplier_8.drop([0,1,2,3,4], axis = 0, inplace =True)



supplier_8.rename(columns = {'إسم الصنف' : 'Arabic Name',
                       'السعر' : 'Price',
                       supplier_8.columns[3] : 'supplier_8'}, inplace = True)


supplier_8['new Name'] = supplier_8['Arabic Name'].str.split(" ").str[0]


supplier_8['conc'] = supplier_8['Arabic Name'].str.extract('(\d+)')


supplier_8 = supplier_8[['new Name','Price','supplier_8','conc']]


supplier_8.head(5)

4  new Name Price supplier_8 conc
5       ابى   120         29  NaN
6    ابيتنس   6.7         34   30
7  ابيجرييك    75         27  NaN
8  ابيدكسون   7.5         32  NaN
9  ابيدكسون   7.5         15  NaN

In [20]:
supplier_9 = pd.read_excel(r'excel files/supplier9.xlsx')

supplier_9

     نقدى   سعر ج  الكود                       الصنف
0     30.0   11.0     23  ابلونج نوفالجين صغير  جديد
1     30.0    6.7   8340                ابيتنس 100 م
2     41.0   70.0    246            ارتيك اقراص جديد
3     28.0  195.0    251                ارث فرى3شريط
4      9.0  164.5   8102                اركوكسيا 90م
..     ...    ...    ...                         ...
241   16.0  255.0  10290     هيرو او ار اس عبوه 3كيس
242   14.0   33.0   7911           ويندبين 10مجم 30ق
243   14.0   21.0   7912             ويندبين5مجم 30ق
244   31.0   18.0   7971            يوريكنترول اقراص
245   10.0  220.0   9929      يونيتركسات 5امبول جديد

[246 rows x 4 columns]

In [21]:
supplier_9.rename(columns = {'الصنف' : 'Arabic Name',
                       'سعر ج' : 'Price',
                       supplier_9.columns[0] : 'supplier_9'}, inplace = True)


supplier_9['new Name'] = supplier_9['Arabic Name'].str.split(" ").str[0]


supplier_9['conc'] = supplier_9['Arabic Name'].str.extract('(\d+)')

supplier_9 = supplier_9[['new Name','Price','supplier_9','conc']]

supplier_9.head(5)

   new Name  Price  supplier_9 conc
0    ابلونج   11.0        30.0  NaN
1    ابيتنس    6.7        30.0  100
2     ارتيك   70.0        41.0  NaN
3       ارث  195.0        28.0    3
4  اركوكسيا  164.5         9.0   90

In [22]:
supplier_10 = pd.read_excel(r'excel files/supplier10.xlsx')


supplier_10

     مندوب  سعر ج  الكود                         الصنف
0     30.0   21.0   7139            ابل لايت اقراص /20
1     39.0    8.0   7413              ابيمول اقراص/ك60
2     27.0   26.0   9454              اترابكس 4 ك /420
3     31.0  180.0  16456  اتكوجليفلوزين 25م س180ج/ك112
4     31.0  180.0  16455    اتكوجليفلوزين10م س180/ك112
..     ...    ...    ...                           ...
625   34.0  192.5  16182          يورونيميا امبول /ك10
626   31.0   36.0   5703       يوريبان   اقراص س.ج/ك10
627   37.0  185.0  12546           يوفى بلوك كريم 185ج
628   63.0   27.5  16683         يوكال جيل صغير 27.5/ف
629    7.0  220.0  14592  يونى تركسات 50 ملي فيال/ك144

[630 rows x 4 columns]

In [23]:
supplier_10.rename(columns = {supplier_10.columns[3]: 'Arabic Name',
                        supplier_10.columns[1]: 'Price',
                        supplier_10.columns[0] : 'supplier_10'}, inplace = True)


supplier_10['new Name'] = supplier_10['Arabic Name'].str.split(" ").str[0]


supplier_10['conc'] = supplier_10['Arabic Name'].str.extract('(\d+)')


supplier_10 = supplier_10[['new Name','Price','supplier_10','conc']]


supplier_10.head(5)

           new Name  Price  supplier_10 conc
0               ابل   21.0         30.0   20
1            ابيمول    8.0         39.0   60
2           اترابكس   26.0         27.0    4
3     اتكوجليفلوزين  180.0         31.0   25
4  اتكوجليفلوزين10م  180.0         31.0   10

In [24]:
supplier_11 = pd.read_excel(r'excel files/supplier11.xlsx')

supplier_11

    أرصده المخازن\n                         Unnamed: 1  Unnamed: 2 Unnamed: 3
0               NaN                                NaN         NaN        NaN
1               NaN                                NaN         NaN        NaN
2               NaN                                NaN         NaN        NaN
3               NaN                                NaN         NaN        NaN
4         رقم الصنف                          إسم الصنف   خصم اساسى      السعر
..              ...                                ...         ...        ...
535           12453  يتروكيور اقراص سعر قديم الباكو 60          33         84
536           13898  يوروسولفين سعر 23.5 جديد الباكو50          30       23.5
537           12147           يورونيميا امبول/الباكو10          30      192.5
538            1233                     يوفى بلوك كريم          38        165
539             490   يونيكتام750فيال الباكو 64 المهن           37         20

[540 rows x 4 columns]

In [25]:
supplier_11.columns = supplier_11.iloc[4]

supplier_11.drop([0,1,2,3,4], axis = 0, inplace =True)

supplier_11.rename(columns = {supplier_11.columns[1]: 'Arabic Name',
                        supplier_11.columns[3]: 'Price',
                        supplier_11.columns[2] : 'supplier_11'}, inplace = True)


supplier_11['new Name'] = supplier_11['Arabic Name'].str.split(" ").str[0]


supplier_11['conc'] = supplier_11['Arabic Name'].str.extract('(\d+)')


supplier_11 = supplier_11[['new Name','Price','supplier_11','conc']]

supplier_11.head(5)

4         new Name Price supplier_11 conc
5              ابى   120          31  NaN
6              ابى    55          30  NaN
7        ابيفورتيل    60          33   60
8    اتكوجليفلوزين   180          28   10
9  اتكوجليفلوزين25   180          28   25

In [26]:
supplier_12 = pd.read_excel(r'excel files/supplier12.xlsx')

supplier_12

,أرصده المخازن\n,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,رقم الصنف,إسم الصنف,السعر,خصم اساسى
...,...,...,...,...
392,13376,هيبتا بانثينول لايت لوشن للجسم 100م,90,36
393,13378,هيبتا بانثينول ماكس 50مجم,69,36
394,12509,هيرودكس شامبو250مجم,169,35
395,8963,هيرودوكس سيرم 120مل /,219,35
396,4425,يوروزول اقراص / العامرية,11.5,32

In [27]:
supplier_12.columns = supplier_12.iloc[4]


supplier_12.drop([0,1,2,3,4], axis = 0, inplace =True)


supplier_12.rename(columns = {'إسم الصنف' : 'Arabic Name',
                             'السعر' : 'Price',
                             supplier_12.columns[3] : 'supplier_12'}, inplace = True)


supplier_12['new Name'] = supplier_12['Arabic Name'].str.split(" ").str[0]



supplier_12['conc'] = supplier_12['Arabic Name'].str.extract('(\d+)')


supplier_12 = supplier_12[['new Name','Price','supplier_12','conc']]


supplier_12.head(5)

4          new Name Price supplier_12 conc
5           ابروفال    55          15  150
6           ابيفاسى   211           7  NaN
7         ابيفورتيل    60          36  NaN
8  اتكوبريلاكس50مجم    24          37   50
9       اتوموريلاكس   100          26  NaN

In [28]:
# create a list of all suppliers dataframes

supplier_list = [supplier_1, supplier_2, supplier_3, supplier_4, supplier_5,
                 supplier_6, supplier_7, supplier_8, supplier_9,
                 supplier_10, supplier_11, supplier_12]




# making a loop to merge the original dataframe with all suppliers dataframes and create a list of merged dataframes

merged_list=[]
for supplier in supplier_list:
    merged = original_df.merge(supplier, how='inner',on=['new Name','Price','conc'])
    merged_list.append(merged)




# Merging all dataframes in the merged_list into one final dataframe

final_df = merged_list[0]    
for df in merged_list[1:]:
    final_df = final_df.merge(df, how='outer')
    
    
    
    
# drop the 'new Name' and 'conc' columns as they are not needed in the final output

final_df.drop(['new Name','conc'], axis = 1, inplace = True)

In [29]:
final_df.head(5)

,Product ID,Item,Arabic Name,Price,required,supplier_1,supplier_2,supplier_3,supplier_4,supplier_5,supplier_6,supplier_7,supplier_8,supplier_9,supplier_10,supplier_11,supplier_12
0,14,ADOL SINUS 24 CAPLETS,ادول ساينس 24 كابلت,24.0,1.0,NaN,NaN,NaN,25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,53,OST-MAP 60MG 20 CAPS.,اوست ماب 60 مجم 20 كبسولة,26.0,1.0,NaN,NaN,NaN,NaN,NaN,26,NaN,NaN,NaN,NaN,31,NaN
2,152,APIFORTYL 30 CAPSULE,ابيفورتيل 30 كبسولة,60.0,47.0,NaN,NaN,NaN,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,162,LANTANON 30MG 10 CAPS.,لانتانون 30 مجم 10 كبسولات,45.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38,NaN,39.0,NaN,NaN
4,210,CONVENTIN 400MG 30 CAPS.,كونفنتين 400 مجم 30 كبسولة,111.0,24.0,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# history_df contains previous discount data

history_df = pd.read_excel(r'excel files/History data.xlsx')



# identify maximum discount for each unique product in the history data

history_max_discount = history_df.groupby('Product name')['Discount %'].max().reset_index()

history_max_discount.rename(columns={'Discount %': 'Max Discount %'}, inplace=True)



# unifying some columns name to be matched with final_df dataframe

history_max_discount.rename(columns={'Product name': 'Item'}, inplace=True)




# meging the history_max_discount dataframe with final_df to add the maximum discount percentage for each product

final_df = final_df.merge(history_max_discount, how='left',on='Item')




# highlight the maximum discount percentage across all suppliers for each unique product

df_final = final_df.style.highlight_max(subset =['supplier_1', 'supplier_2','supplier_3','supplier_4','supplier_5','supplier_6','supplier_7',
                                               'supplier_8','supplier_9','supplier_10','supplier_11','supplier_12','Max Discount %'],
                                      color = 'lightgreen', axis = 1)

df_final

In [31]:
# ! pip install xlsxwriter

# Save the final DataFrame to an Excel file with formatting

with pd.ExcelWriter('Result/Best Discounts.xlsx', engine='xlsxwriter') as writer:
    df_final.to_excel(writer, sheet_name='Best Discounts', index=False)